services:
  backapp:
    image: backapp:backapp
    environment:
      SERVER_PORT: 8081

  frontapp:
    image: frontapp:frontapp
    environment:
      BACK_URL: 'http://backapp:8081'
    ports:
    - 8080:8080